[Rule]
# 局域网
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Lan/Lan.list,DIRECT

# 中国域名
RULE-SET,中国域名规则集,DIRECT

# 中国大陆 IP
GEOIP,CN,DIRECT

# 其他全部代理
FINAL,PROXY
