# Load environment variables
[[ -f "$HOME/.config/zsh/exports.zsh" ]] && source "$HOME/.config/zsh/exports.zsh"

# Load Zsh options
[[ -f "$HOME/.config/zsh/options.zsh" ]] && source "$HOME/.config/zsh/options.zsh"

# Load aliases
[[ -f "$HOME/.config/zsh/aliases.zsh" ]] && source "$HOME/.config/zsh/aliases.zsh"

# Load plugins
[[ -f "$HOME/.config/zsh/plugins.zsh" ]] && source "$HOME/.config/zsh/plugins.zsh"

# Load prompt config
[[ -f "$HOME/.config/zsh/prompt.zsh" ]] && source "$HOME/.config/zsh/prompt.zsh"

# Load sdkman
[[ -f "$HOME/.config/zsh/sdkman.zsh" ]] && source "$HOME/.config/zsh/sdkman.zsh"


### ↓↓↓ KEEP THIS CLEAN: anything below is auto-generated by installers ↓↓↓
