worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # http 全局策略
    include /etc/nginx/conf.d/*.conf;

    # upstream
    include /etc/nginx/upstreams/*.conf;

    # 已启用的网站
    include /etc/nginx/sites-enabled/*.conf;
}
