services:
  jupyter:
    image: quay.io/jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - /Users/xuehui/jupyter:/home/jovyan/work  # 挂载工作目录
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - TZ=Asia/Shanghai
    command: >
      start-notebook.py
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.ip=0.0.0.0
      --ServerApp.open_browser=False
      --ServerApp.port=8888
      --ServerApp.root_dir=/home/jovyan/work
