# 启用缓存
proxy_cache my_cache;

# 缓存 GET / HEAD
proxy_cache_methods GET HEAD;

# 成功响应缓存
proxy_cache_valid 200 1h;

# 后端异常时允许使用旧缓存
proxy_cache_use_stale
    error
    timeout
    updating
    http_500
    http_502
    http_503
    http_504;
