# =========================
# SSL / TLS Certificate
# =========================

# SSL/TLS 服务器证书
# fullchain.pem 通常包含：
#   1. 当前域名的服务器证书
#   2. 中间 CA 证书链
#
# 推荐使用 fullchain.pem，确保客户端能够完整验证证书链
ssl_certificate
    /etc/nginx/ssl/yourdomain.com/fullchain.pem;


# SSL/TLS 私钥
# 必须与 fullchain.pem 中的服务器证书匹配
#
# 注意：
#   私钥文件应严格限制文件权限，避免被非授权用户读取
ssl_certificate_key
    /etc/nginx/ssl/yourdomain.com/privkey.pem;


# 受信任的 CA 证书链
# 用于 Nginx 验证客户端证书或进行相关 TLS 证书链验证
#
# chain.pem 通常包含中间 CA 证书
ssl_trusted_certificate
    /etc/nginx/ssl/yourdomain.com/chain.pem;
