global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "alert.rules.yml"
  
scrape_configs:
  # - job_name: 'mysqld-exporter'
  #   static_configs:
  #     - targets: ['mysqld-exporter:9104']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
