# =========================
# Gzip
# =========================

gzip on;

gzip_min_length 1k;

gzip_comp_level 5;

gzip_vary on;

gzip_types
    text/plain
    text/css
    application/json
    application/javascript
    text/xml
    application/xml
    application/xml+rss
    text/javascript;
