# =========================
# Proxy Buffer
# =========================

proxy_buffers 8 16k;

proxy_buffer_size 4k;


# =========================
# Proxy Cache Zone
# =========================

proxy_cache_path /data/nginx/cache
    levels=1:2
    keys_zone=my_cache:10m
    max_size=1g
    inactive=1h
    use_temp_path=off;


# =========================
# 缓存异常回退
# =========================

proxy_cache_use_stale
    error
    timeout
    updating
    http_500
    http_502
    http_503
    http_504;
