# =========================
# Rate Limit Zones
# =========================

limit_req_zone
    $binary_remote_addr
    zone=per_ip:10m
    rate=10r/s;


limit_conn_zone
    $binary_remote_addr
    zone=per_ip_conn:10m;
