server {

    listen 80;

    server_name yourdomain.com;

    # ACME 证书续签
    include /etc/nginx/snippets/acme-challenge.conf;

    # 其他请求全部 HTTPS
    location / {

        add_header Cache-Control "no-store";

        return 301 https://$host$request_uri;
    }
}
