# stylua .    # 格式化往前目录下所有lua文件代码
# stylua xxx.lua  # 指定格式化代码


# 缩进类型：Spaces 或 Tabs
indent_type = "Spaces"
# 缩进宽度
indent_width = 2
# 每行最大字符数
column_width = 120
# 行尾字符："Unix" 或 "Windows"
line_endings = "Unix"
# 字符串引号样式："AutoPreferDouble", "AutoPreferSingle", "ForceDouble", "ForceSingle"
quote_style = "AutoPreferDouble"
# 是否调用链换行
call_parentheses = "Always"
# 是否对表中的键进行排序
sort_requires = true
# 是否保持多行注释的格式
preserve_newlines = true
# 表达式周围是否需要空格
collapse_simple_statement = "Never"
# 是否允许单行表达式
single_statement = false
# 是否在操作符周围添加空格
spaces_around_operators = true
# 是否在最后一个表项后添加逗号
trailing_table_separator = "Always"
# 是否对齐连续的赋值语句
align_continuous_assign_statements = true
# 是否对齐连续的表字段
align_continuous_table_statements = true
