name: Qodana Python Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: jetbrains/qodana-python
  REPORT_DIR: .github/workflows/reports/qodana-report

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 更新到 v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3  # 更新到 v3

      - name: Debug - List files in Docker container
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}
          docker run --rm -v ${{ github.workspace }}:/data ${{ env.DOCKER_IMAGE }} ls -alh /data

      - name: Run Qodana analysis
        run: |
          mkdir -p ${{ env.REPORT_DIR }}
          docker pull ${{ env.DOCKER_IMAGE }}
          docker run --rm -v ${{ github.workspace }}:/data -v ${{ env.REPORT_DIR }}:/data/qodana/report ${{ env.DOCKER_IMAGE }} --save-report --source-directory /data --report-directory /data/qodana/report

      - name: Upload Qodana report
        uses: qodana/qodana-action@v4
        with:
          reportDirectory: ${{ env.REPORT_DIR }}
