name: Ruff Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Python Code with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # 将 Ruff 输出保存到文件
      - name: Run Ruff
        run: |
          ruff check . | tee ruff.log

      # 如果 Ruff 检查失败，显示 Ruff 的输出日志
      - name: Show Ruff logs
        if: failure()
        run: cat ruff.log
